default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: petition_development

test:
  <<: *default
  database: petition_test

production:
  <<: *default
  database: petition_production
