# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d64b9c3e51f1ec5a7020c6e5213a1b5584afe6c43d8c3b424d1b52a9534f3a54f4aee529fb32dd1d22a75d5f80fe50cf7971b495929fe6556472cc99d987bd5

test:
  secret_key_base: afa881babf2d7330f985f532e1e5729532107e1b2b64b3797f3265f2f159ae20b009b936c7e7050950c26f666ba17e6cf9929f015554e7eabfc633c703711a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
